### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [robinwhittleton/aleksandr-kuprin_short-fiction_j-m-murray#1]
- [x] There are words that contain ligatures that can be replaced with the expanded characters (Læstrygonian, gynæceum, Chaldæa/Chaldæan, amphoræ, æthereal, Judæa, Phœnix, and Phœnicia/Phœnician) ([SEMOS 8.6.](https://standardebooks.org/manual/1.6.2/single-page#8.6)).

- [x] In the endnotes there are several citations of passages from the Bible.  "All chapter and verse numbers are written in Arabic numerals. Similarly, if a book being cited is a “numbered” book, the number is also written in Arabic numerals" ([SEMOS 8.17.4.1.1.](https://standardebooks.org/manual/1.6.2/single-page#8.17.4.1.1)).
The semicolons between the books and their chapters can also be removed.

**Comment by robinwhittleton** [comment]
Thanks Emma, those are both fixed now.
